### ISSUE TITLE
Using the `summary` endpoint to find IPs of users

### ISSUE THREAD

**Issue by fuglede** [shamblesides/turfwar#5]
It is currently possible to use the `summary` endpoint to efficiently find the IP of a given user (e.g. through binary search), assuming that they only appear with a single IP (as is the case for many). Since some users likely use handles that are easily tied to identities (names, emails, social media handles, ...), this allows you to tie IPs to people. Is this intentional? It seems a little ... uncomfortable. IPs are considered PII under the GDPR.

It's a wonderful game though!

**Comment by shamblesides** [comment]
Good points! And the route is no longer actually used by the homepage anymore. I just removed it for now.

**Comment by fuglede** [comment]
And `user.html` is a great way around the problem!
