### ISSUE TITLE
Board per IP subnet

### ISSUE THREAD

**Issue by U-siro** [shamblesides/turfwar#6]
I previously used /summary endpoint for checking my rank in this range.
However this endpoint has been deprecated, so I want /board endpoint with subnet options, and returns the rank.

As GDPR requirements, It should be forced for /8.

**Comment by shamblesides** [comment]
Sounds good, I'll bring back something similar that's locked to /8

**Comment by shamblesides** [comment]
Done, I just brought back the summary route but locked it to <= 8
